
services:
  app:
    build: .
    container_name: reproductor-casero
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - .:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "/almacenamiento/videos:/app/src/videos"
 