

services:
  app:
    build: .
    container_name: reproductor-casero
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - direccion de la carpeta:/app/src/videos
    deploy:
      resources:
        limits:
          memory: 1024M